#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from kohaku_service_examples.kohaku_servo_alloff_node import ServoAllOffExampleNode

try:
    this_node = ServoAllOffExampleNode()
    this_node.run()
except rospy.ROSInterruptException:
    pass
