#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from kohaku_moveit_examples.gripper_example_node import GripperExampleNode

try:
    this_node = GripperExampleNode()
    this_node.run()
except rospy.ROSInterruptException:
    pass
