#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from kohaku_moveit_examples.motion_example_node import MotionExampleNode

try:
    this_node = MotionExampleNode()
    this_node.run()
except rospy.ROSInterruptException:
    pass
