#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from kohaku_moveit_examples.show_eefpose_node import ShowEefposeNode

try:
    this_node = ShowEefposeNode()
    this_node.run()
except rospy.ROSInterruptException:
    pass
